{
 "title": "Transferências de Tarefas",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total de Transferências de Tarefas",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(task_transfers_count_total)",
     "legendFormat": "Total de Transferências"
    }
   ]
  },
  {
   "title": "Tarefas Transferidas por Origem",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(fromUserId) (task_transfers_count_total)",
     "legendFormat": "De: Usuário {{fromUserId}}"
    }
   ]
  },
  {
   "title": "Tarefas Transferidas por Destino",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(toUserId) (task_transfers_count_total)",
     "legendFormat": "Para: Usuário {{toUserId}}"
    }
   ]
  }
 ]
}