{
 "title": "Todo App",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Contador de Tarefas Arquivadas",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "http_server_duration_milliseconds_count{http_route=\"/tasks/:id/archive\"}",
     "legendFormat": "Tarefas Arquivadas"
    }
   ]
  },
  {
   "title": "Requisições HTTP",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(http_route, http_method) (http_server_duration_milliseconds_count)",
     "legendFormat": "{{http_method}} {{http_route}}"
    }
   ]
  },
  {
   "title": "Tempo Médio de Resposta HTTP (ms)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum by(http_route, http_method) (http_server_duration_milliseconds_sum) / sum by(http_route, http_method) (http_server_duration_milliseconds_count)",
     "legendFormat": "{{http_method}} {{http_route}}"
    }
   ]
  },
  {
   "title": "Status da Aplicação",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "up{job=\"otel-collector\"}",
     "legendFormat": "Aplicação Ativa"
    },
    {
     "expr": "scrape_duration_seconds{job=\"otel-collector\"}",
     "legendFormat": "Tempo de Coleta"
    }
   ]
  }
 ]
}