apiVersion: 1

datasources:
  - name: Jaeger
    type: jaeger
    access: proxy
    uid: jaeger
    url: http://jaeger:16686
    jsonData:
      nodeGraph:
        enabled: true
      spanBar:
        type: "Duration"
    version: 1
    editable: true 